DROP TABLE IF EXISTS ARITHMETIC_CALCULATION;

CREATE TABLE ARITHMETIC_CALCULATION(
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  EXPRESSION VARCHAR(250) NOT NULL,
  RESULT VARCHAR(250) NOT NULL
);

INSERT INTO ARITHMETIC_CALCULATION(EXPRESSION, RESULT) VALUES
  ('(2+3)/5', '1.0'),
  ('(3+5)*4', '32.0');